// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ticowxyacvnzsukdpzjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpY293eHlhY3ZuenN1a2Rwemp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODYxMzAsImV4cCI6MjA2MDM2MjEzMH0.0Zs2d8skWsoZ2VRVoXjBuG5DxTzks933hphkgPo8hRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);