// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpbgmoepwzpbidnqktwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwYmdtb2Vwd3pwYmlkbnFrdHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTI3ODIsImV4cCI6MjA1NjY2ODc4Mn0.Tfsj_Tz71KrU5lBl7JkqHu14QKLeBuHUdpqihag7ll4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);